### ISSUE TITLE
Running testcontainers in github Action

### ISSUE THREAD

**Issue by sylhare** [sylhare/SpaceStack#1]
With docker new pullPolicy restriction, it's getting trickier and often there are some unfortunate:

```bash
org.testcontainers.containers.ContainerFetchException: Can't get Docker image:
RemoteDockerImage(imageName=mongo:4.0.10, imagePullPolicy=DefaultPullPolicy())
```

I believe there's a way to pass through those restriction using your own docker account, or by fiddling with the testcontainer configurations, just have to find it.

**Comment by sylhare** [comment]
Well I just pull manually the images beforehand so that testcontainers would have them available right away:

```yaml
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}      
    - name: Pull docker images
      run: |
        docker pull mongo:4.0.10  
        docker pull testcontainers/ryuk:0.3.0 
```
